services:
  reset-app:
    image: homecloudcloud/forgot-password:1.0.17
    container_name: reset-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.forgotpassword.rule=PathPrefix(`/forgot-password`)
      - traefik.http.routers.forgotpassword.tls=true
    env_file:
      - /var/lib/password-reset/config.env
    volumes:
      - ./reset.sh:/reset.sh:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - :80
