#!/bin/sh
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.
. /usr/share/openmediavault/scripts/helper-functions

set -e

# Make sure that only one instance of this shell script is running at
# the same time.
LOCK_FILE=/run/openmediavault-iptables.lock
if ! mkdir "${LOCK_FILE}"; then
    omv_error "Locking failed, another job is running"
    exit 0
fi

trap "rm -rf ${LOCK_FILE}" 0 1 2 3 5 15

case "$1" in
    start)
        iptables -t filter -F INPUT
        iptables -t filter -F OUTPUT
        iptables -A INPUT -p tcp --source 0.0.0.0/0 --destination 0.0.0.0/0 --dport 22 -j ACCEPT
        iptables -A INPUT -p tcp --source 0.0.0.0/0 --destination 0.0.0.0/0 --dport 80 -j ACCEPT
        iptables -A INPUT -p tcp --source 0.0.0.0/0 --destination 0.0.0.0/0 --dport 443 -j ACCEPT
        iptables -A INPUT -p all --source 127.0.0.1/32 --destination 127.0.0.1/32 -j ACCEPT
        iptables -A OUTPUT -p all -j ACCEPT
        iptables -A INPUT -p all -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED
        iptables -A INPUT -p udp --dport 9995 -j ACCEPT
        iptables -A INPUT -p icmp -j ACCEPT
        iptables -A INPUT -p tcp --dport 8097 -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED,NEW
        iptables -A INPUT -p udp --dport 8097 -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED,NEW
        iptables -A INPUT -p udp --dport 22302 -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED,NEW
        iptables -A INPUT -p tcp --dport 22302 -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED,NEW
        iptables -A INPUT -p udp --dport 67:68 -j ACCEPT
        iptables -A INPUT -p udp --dport 2284 -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED,NEW
        iptables -A INPUT -p tcp --dport 2284 -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED,NEW
        iptables -A INPUT -p tcp --dport 445 -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED,NEW
        iptables -A INPUT -p udp --dport 137:138 -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED,NEW
        iptables -A INPUT -p tcp --dport 139 -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED,NEW
        iptables -A INPUT -p tcp --source 100.0.0.0/8 --dport 8000 -j ACCEPT -m conntrack --ctstate RELATED,ESTABLISHED,NEW
        iptables -A INPUT -p udp --dport 5353 -j ACCEPT
        iptables -A INPUT -p all --destination 255.255.255.255 -j ACCEPT
        iptables -A INPUT -p udp --sport 53 -j ACCEPT
        iptables -A INPUT -p udp --dport 53 -j ACCEPT
        iptables -A INPUT -p udp --sport 123 -j ACCEPT
        iptables -A INPUT -p udp --dport 123 -j ACCEPT
        iptables -A INPUT -p tcp --dport 5000 -j REJECT
        iptables -A INPUT -p tcp --source 0.0.0.0/0 --destination 0.0.0.0/0 -j REJECT
        iptables -A INPUT -p udp --source 0.0.0.0/0 --destination 0.0.0.0/0 -j REJECT
        iptables -A INPUT -p udp --dport 5000 -j REJECT
        ;;

    stop)
        iptables -t filter -F INPUT
        iptables -t filter -F OUTPUT
        iptables -P INPUT ACCEPT
        iptables -P OUTPUT ACCEPT
        ip6tables -t filter -F INPUT
        ip6tables -t filter -F OUTPUT
        ip6tables -P INPUT ACCEPT
        ip6tables -P OUTPUT ACCEPT
        ;;
esac

exit 0
