entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  immich:
    address: ":2284"
    transport:
      respondingTimeouts:
        readTimeout: 1200s
        idleTimeout: 1200s
        writeTimeout: 1200s
  joplin:
    address: ":22302"
    transport:
      respondingTimeouts:
        readTimeout: 1200s
        idleTimeout: 1200s
        writeTimeout: 1200s
  jellyfin:
    address: ":8097"
  paperless-ngx:
    address: ":8001"
  duplicati:
    address: ":8200"
providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik/dynamic
    watch: true
api:
  insecure: false
  dashboard: false

accessLog:
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep 

log:
  level: INFO
