version: "1.0"
type: route
data:
  url: "/services/clamav/settings"
  title: _("Settings")
  editing: true
  notificationTitle: _('Updated Antivirus settings.')
  component: omv-services-clamav-settings-form-page
