version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.password-manager.update"
  position: 70
  text: _("Update")
  icon: "mdi:update"
  url: "/startconfiguration/apps/password-manager/update"