version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.notes.password"
  position: 70
  text: _("Password")
  icon: network
  url: "/startconfiguration/apps/notes/password"