version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.photos.restart"
  position: 70
  text: _("Status")
  icon: "mdi:list-status"
  url: "/startconfiguration/apps/photos/restart"