version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.vpn.tailscaleconfig"
  position: 60
  text: _("Configure")
  icon: "mdi:cog"
  url: "/startconfiguration/vpn/tailscaleconfig"