version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.password-manager.access"
  position: 70
  text: _("Access")
  icon: connection
  url: "/startconfiguration/apps/password-manager/access"