version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.urbackup.cloudstorage"
  position: 80
  text: _("CloudStorage")
  icon: drive
  url: "/startconfiguration/apps/urbackup/cloudstorage"