version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.password-manager"
  position: 70
  text: _("Passwords")
  icon: "mdi:safe"
  url: "/startconfiguration/apps/password-manager"