version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.password-manager.backup"
  position: 70
  text: _("Backup")
  icon: "mdi:content-copy"
  url: "/startconfiguration/apps/password-manager/backup"