version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.drive.backup"
  position: 80
  text: _("Backup")
  icon: "mdi:content-copy"
  url: "/startconfiguration/apps/drive/backup"