version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.media.password"
  position: 70
  text: _("Password")
  icon: "mdi:lock-reset"
  url: "/startconfiguration/apps/media/password"