version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.cloudbackup"
  position: 70
  text: _("CloudBackup")
  icon: "mdi:content-copy"
  url: "/startconfiguration/apps/cloudbackup"