version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.paperless.access"
  position: 70
  text: _("Access")
  icon: connection
  url: "/startconfiguration/apps/paperless/access"