version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.photos.backup"
  position: 70
  text: _("Backup")
  icon: "mdi:content-copy"
  url: "/startconfiguration/apps/photos/backup"